apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productcatalogservicephp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalogservicephp
    spec:
      containers:
        - name: productcatalogservicephp
          image: productcatalogservicephp
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 350m
              memory: 350Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - name: fpm
              containerPort: 7001
#          volumeMounts:
#            - mountPath: /data/code
#              name: code
#            - mountPath: /var/log
#              name: log
      volumes:
        - name: code
          emptyDir: {}
        - name: log
          hostPath:
            path: /var/log
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservicephp
spec:
  type: ClusterIP
  selector:
    app: productcatalogservicephp
  ports:
    - name: grpc
      port: 7001
      targetPort: 7001

