apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          image: productcatalogservice
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 350m
              memory: 350Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - name: fpm
              containerPort: 7001
      volumes:
        - name: code
          emptyDir: {}
        - name: log
          hostPath:
            path: /var/log
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: LoadBalancer
  selector:
    app: productcatalogservice
  ports:
    - name: grpc
      port: 7001
      targetPort: 7001

